# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: app-client
  mvc:
    view:
      prefix: /templates/
      suffix: .html

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost

# HTTP Server (Tomcat) Port
  server:
    port: 8080

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false


logging:
  level:
    com.zisal.client.app: DEBUG