spring:
  application:
    name: zipkin-server
  boot:
    admin:
      url: http://localhost:8989
      username: admin
      password: password

server:
  port: 9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    region: default
    registryFetchIntervalSeconds: 5


info:
  app:
    name: Zipkin Server Application
    description: Zipkin Server Application
    version: 1.0.0
