spring:
  application:
    name: zipkin-server

server:
  port: 9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    region: default
    registryFetchIntervalSeconds: 5


info:
  app:
    name: Zipkin Server Application
    description: Zipkin Server Application
    version: 1.0.0
