#basic auth creddentials
security:
  user:
    name: client
    password: client

spring:
  boot:
    admin:

      #configs to connect to a secured server
      url: http://localhost:8989
      username: admin
      password: admin

    #configs to give secured server info
      client:
        metadata:
          user:
            name: ${security.user.name}
            password: ${security.user.password}

  #app config
  application: name=spring-boot-admin-client


server:
  port: 9000