spring:
  application:
    name: config-server
  boot:
    admin:
      url: http://localhost:8989
      username: admin
      password: password
server:
    port: 8888


management:
    security:
        enabled: false

# Discovery Server Access
eureka:
    client:
      registerWithEureka: false
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/