spring:
    application:
        name: config-server

server:
    port: 8888


management:
    security:
        enabled: false

# Discovery Server Access
eureka:
    client:
      registerWithEureka: false
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/