### Spring properties
# Service registers under this name
spring:
  application:
    name: product-api


  jpa:
    show-sql :  true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_simple_microservice
    username: root
    password: P@ssw0rd

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 3333

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
